# SAM configuration file for Lambda Cost and Performance Optimization project

version = 0.1

[default.global.parameters]
stack_name = "lambda-cost-performance-optimization"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "lambda-cost-performance-optimization"
region = "us-east-1"
image_repositories = []
parameter_overrides = "EnableXRayTracing=true"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
